### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jo24** [CryptoRobotFr/backtest_tools#4]
Bon code et tres bonnes explications dans vos vidéo, mais si je peut me permettre, le module multiprocessing serait tres utile dans vos script, je pense notament dans celui des divergences sur les petits timeframes...
Ca rend le code un peut moin clair pour les débutant, mais c'est tellement plus rapide et ca demande pas beaucoup de modif... mais bon perso ca me derange pas ;)
Merci pour votre travail !

def get_df_top_divergence_mp(index,row,df_top, df_top_indicator, indicator_name, base_column, top_concordance, max_period_check,min_window_diff):
    top_scopes = []
    min_scope = -1000000
    min_window_diff = 10
    top_indicator_index = list(df_top_indicator["iloc"])
    try:
        current_df = df_top.copy().loc[df_top.index > index]
        base_point_date = row["date"]
        base_point_iloc = row["iloc"]
        base_point_value = row[base_column]
        base_point_indicator_value = row[indicator_name]
        for current_row in current_df.to_dict(orient="records"):
            scope = (current_row[base_column] - base_point_value) / (current_row["iloc"] - base_point_iloc)
            if base_point_iloc + max_period_check < current_row["iloc"]:
                break
            elif (current_row["iloc"] - base_point_iloc < min_window_diff):
                min_scope = scope
                continue
            elif (scope < min_scope):
                continue
            else:
                min_scope = scope
                if top_concordance == False or ((current_row["iloc"] in top_indicator_index) and (base_point_iloc in top_indicator_index)):
                    indicator_scope = (current_row[indicator_name] - base_point_indicator_value) / (current_row["iloc"] - base_point_iloc)
                    top_scopes.append({
                        "start_date": base_point_date,
                        "end_date": current_row["date"],
                        "start_iloc": base_point_iloc,
                        "end_iloc": current_row["iloc"],
                        "start_value": base_point_indicator_value,
                        "end_value": current_row["close"],
                        "scope":scope,
                        "start_indicator_value": base_point_value,
                        "end_indicator_value": current_row["rsi"],
                        "indicator_scope": indicator_scope
                    })
    except:
        pass
    return top_scopes

def get_df_top_divergence(df_top, df_top_indicator, indicator_name, base_column="close", top_concordance=False, max_period_check=100,min_window_diff=10):
    result=[]
    pool=multiprocessing.Pool(processes=24)
    for index, row in df_top.iterrows():
        result.append(pool.apply_async(func=get_df_top_divergence_mp,args=(index,row,df_top, df_top_indicator, indicator_name, base_column, top_concordance, max_period_check,min_window_diff)))
    pool.close()
    pool.join()
    result=[x.get() for x in result]
    top_scopes=[]
    for x in result:
        top_scopes.extend(x)
    return pd.DataFrame(top_scopes)

**Comment by CryptoRobotFr** [comment]
Hello en effet oui cela serait plus efficace, après pour ces codes je n'ai pas forcément besoin de la meilleur performance. Et comme tu l'as dit cela rend le code un peu moins accessible aux débutants. 
Mais par contre oui j'utilise le multiprocessing pour de l'optimisation de paramètre par exemple
