### ISSUE TITLE
Fast dump Binance CandleSticks 1m sur les 2 dernières heures

### ISSUE THREAD

**Issue by Olidefo** [CryptoRobotFr/backtest_tools#5]
bonjour
J'ai une question: comment dois je modifier le fichier .js pour téléchrager les CandleSticks de Binance avec 1 intervalle de temps de 1min et nom de 1h sur 1 journée mais ne prendre que les 3 dernières heures par exemple, ou même les 5 dernières minutes  ?
Le but étant de faire un dump de environ 100 à 150 Crytos en même temps !
Continuez comme ça: contenu vraiment TOPISSIME ;-)

**Comment by CryptoRobotFr** [comment]
Je te conseille maintenant d'utiliser data_engine.ipynb

```python
exchange_name = "binance"

intervals = ["1m"]

coin_to_dl = ["BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT"]

exchange = ExchangeDataManager(
    exchange_name=exchange_name, 
    path_download="./database/exchanges",
    start_date="2023-01-01 00:00:00"
)

await exchange.download_data(
    coins=coin_to_dl, 
    intervals=intervals
)
```

Qui par exemple ici téléchargera les données en 1m sur "BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT" depuis début 2023.

**Comment by Olidefo** [comment]
MERDE !
Je suis sur mon cul 😉

MERCI MERCI MERCI MERCI

Vous êtes des tueurs car j'avoue vous connaître depuis seulement 1 à 2 mois, et j'ai du mal à reprendre le backlog de toutes les vidéos que vous avez déjà faites et qui me stimules à mort !
A la base je ne suis pas développeur, mais vos vidéos m'ont OUVERT l'esprit .... en recherche donc d'un bot home made qui devrait me pemrettre de ne plus aller à mon boulot ... de merde lol
Le bot nécessite la disponibilité des données de toutes les cryptos (Binance pour l'instant) à la minute près ...

Avoir donc une réponse de vous, avec un code fonctionnel (j'apprends pyhton depuis 1 an , mais js c'est pas encore mon niveau),  ... lors juste un 'ENORME MERCI'

Je n'ai vu votre message que ce matin, je rentre ce soir à lamaison et juste une seule envie: tester cela !!!
A bientôt

Olivier

________________________________
De : Crypto Robot ***@***.***>
Envoyé : vendredi 17 février 2023 09:26
À : CryptoRobotFr/backtest_tools ***@***.***>
Cc : Olidefo ***@***.***>; Author ***@***.***>
Objet : Re: [CryptoRobotFr/backtest_tools] Fast dump Binance CandleSticks 1m sur les 2 dernières heures (Issue #5)


Je te conseille maintenant d'utiliser data_engine.ipynb

exchange_name = "binance"



intervals = ["1m"]



coin_to_dl = ["BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT"]



exchange = ExchangeDataManager(

    exchange_name=exchange_name,

    path_download="./database/exchanges",

    start_date="2023-01-01 00:00:00"

)



await exchange.download_data(

    coins=coin_to_dl,

    intervals=intervals

)

Qui par exemple ici téléchargera les données en 1m sur "BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT" depuis début 2023.

**Comment by Olidefo** [comment]
Hello,

Je dois être très bête, mais je n'arrive pas à faire fonctionner votre pgm !
J'ai le message suivant:
      " await exchange.download_data(
                ^
                SyntaxError: 'await' outside function

J'ai essayé de mettre la commande dans une fonction comme décrit,
J'ai trouvé milles et un work arround ... sans succès !

Pouvez-vous me dire comment j'utilise ce fichier à partir d'un programme Python ?
Merci
Bien cordialement
Olivier
________________________________
De : Olivier DEFOSSE ***@***.***>
Envoyé : mercredi 22 février 2023 15:16
À : CryptoRobotFr/backtest_tools ***@***.***>; CryptoRobotFr/backtest_tools ***@***.***>
Cc : Author ***@***.***>
Objet : RE: [CryptoRobotFr/backtest_tools] Fast dump Binance CandleSticks 1m sur les 2 dernières heures (Issue #5)

MERDE !
Je suis sur mon cul 😉

MERCI MERCI MERCI MERCI

Vous êtes des tueurs car j'avoue vous connaître depuis seulement 1 à 2 mois, et j'ai du mal à reprendre le backlog de toutes les vidéos que vous avez déjà faites et qui me stimules à mort !
A la base je ne suis pas développeur, mais vos vidéos m'ont OUVERT l'esprit .... en recherche donc d'un bot home made qui devrait me pemrettre de ne plus aller à mon boulot ... de merde lol
Le bot nécessite la disponibilité des données de toutes les cryptos (Binance pour l'instant) à la minute près ...

Avoir donc une réponse de vous, avec un code fonctionnel (j'apprends pyhton depuis 1 an , mais js c'est pas encore mon niveau),  ... lors juste un 'ENORME MERCI'

Je n'ai vu votre message que ce matin, je rentre ce soir à lamaison et juste une seule envie: tester cela !!!
A bientôt

Olivier

________________________________
De : Crypto Robot ***@***.***>
Envoyé : vendredi 17 février 2023 09:26
À : CryptoRobotFr/backtest_tools ***@***.***>
Cc : Olidefo ***@***.***>; Author ***@***.***>
Objet : Re: [CryptoRobotFr/backtest_tools] Fast dump Binance CandleSticks 1m sur les 2 dernières heures (Issue #5)


Je te conseille maintenant d'utiliser data_engine.ipynb

exchange_name = "binance"



intervals = ["1m"]



coin_to_dl = ["BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT"]



exchange = ExchangeDataManager(

    exchange_name=exchange_name,

    path_download="./database/exchanges",

    start_date="2023-01-01 00:00:00"

)



await exchange.download_data(

    coins=coin_to_dl,

    intervals=intervals

)

Qui par exemple ici téléchargera les données en 1m sur "BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT" depuis début 2023.

**Comment by Olidefo** [comment]
Bonjour,

Je m'adresse à vous via ce cannal car je n'ai pu en trouver un autre ... Veuillez m'excuser si ce n'est donc pas le bon.

J'ai visionné cette vidéo avec beaucoup d'intérrêt ... et je pense qu'elle pourrait être très intéressante pour la communauté:
https://www.youtube.com/watch?v=EUYwAjj-RLg

De manière très générale, elle utilise l'indicateur "LinReg Candles" de Trading View, et semble d'une simplicité monstrueuse, et des profits que j'imagine très honorables ... profits que je n'ai pu évaluer car si je connais suffisemment python pour me débrouiller seul, je n'ai pas les épaules pour traduire en Python le code source de TradingView.

J'ai imaginé utiliser Trading View pour envoyer un signal vers python, mais il serait préférable je pense inclure directement le code en Python.

Que pensez vous de cette vidéo ?
Que pensez vous de cet indicateur ?

J'ai hâte de vous lire, et plus encore si jamais, de voir une vidéo avec du code python sur cet indicateur

Je vous remercie de tout ce que vous m'avez apris également par toutes vos vidéos,
Bien cordialement
Olivier


________________________________
De : Crypto Robot ***@***.***>
Envoyé : vendredi 17 février 2023 09:26
À : CryptoRobotFr/backtest_tools ***@***.***>
Cc : Olidefo ***@***.***>; Author ***@***.***>
Objet : Re: [CryptoRobotFr/backtest_tools] Fast dump Binance CandleSticks 1m sur les 2 dernières heures (Issue #5)


Closed #5<https://github.com/CryptoRobotFr/backtest_tools/issues/5> as completed.
